arch:
  - amd64
  - ppc64le
language: cpp
compiler:
  - gcc
  - clang
dist: bionic
addons:
  apt:
    packages:
      - cmake
      - libgd-dev
      - libsqlite3-dev
      - libleveldb-dev
      - libpq-dev
      - postgresql-server-dev-all
script: ./util/travis/script.sh
notifications:
  email: false
matrix:
  fast_finish: true
